### ISSUE TITLE
py runGAN.py 2 error

### ISSUE THREAD

**Issue by Azemar** [thunil/TecoGAN#115]
Hello. I managed to pass runGAN.py 0 and 1 without errors, but runGAN.py 2 gives the following:
```
Testing test case 2
[Configurations]:
        output: ./results/metric_log/
        results: ./results/calendar
        targets: ./HR/calendar
End of configuration
Loading model from: D:\TecoGAN\LPIPSmodels\v0.1\alex.pth
metrics.py:216: RuntimeWarning: invalid value encountered in true_divide
  num_data_mean = num_data_sum / num_data_len
Traceback (most recent call last):
  File "metrics.py", line 218, in <module>
    (num_data, cur_list.max(), cur_list.min(), num_data_mean))
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\_methods.py", line 30, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```
My pip list:
Python 3.6.8
Cuda 10.2.89 441.22 win10 + Patch 2

```
Package                 Version
1. absl-py                 0.15.0
2. astor                   0.8.1
3. astunparse              1.6.3
4. backcall                0.2.0
5. bleach                  1.5.0
6. cached-property         1.5.2
7. cachetools              4.2.4
8. certifi                 2021.10.8
9. charset-normalizer      2.0.7
10. colorama                0.4.4
11. cycler                  0.10.0
12. dataclasses             0.8
13. decorator               4.4.2
14. flatbuffers             1.12
15. gast                    0.2.2
16. google-auth             1.35.0
17. google-auth-oauthlib    0.4.6
18. google-pasta            0.2.0
19. grpcio                  1.41.0
20. h5py                    3.1.0
21. html5lib                0.9999999
22. idna                    3.3
23. imageio                 2.9.0
24. importlib-metadata      4.8.1
25. ipython                 7.16.1
26. ipython-genutils        0.2.0
27. jedi                    0.18.0
28. Keras                   2.3.1
29. Keras-Applications      1.0.8
30. Keras-Preprocessing     1.1.2
31. kiwisolver              1.3.1
32. libclang                11.1.0
33. Markdown                3.3.4
34. matplotlib              3.3.4
35. networkx                2.5.1
36. numpy                   1.18.5
37. oauthlib                3.1.1
38. opencv-python           4.5.4.58
39. opencv-python-headless  4.4.0.44
40. opt-einsum              3.3.0
41. pandas                  1.1.5
42. parso                   0.8.2
43. pickleshare             0.7.5
44. Pillow                  8.4.0
45. pip                     21.3.1
46. prompt-toolkit          3.0.21
47. protobuf                3.19.0
48. pyasn1                  0.4.8
49. pyasn1-modules          0.2.8
50. Pygments                2.10.0
51. pyparsing               3.0.0
52. python-dateutil         2.8.2
53. pytz                    2021.3
54. PyWavelets              1.1.1
55. PyYAML                  6.0
56. requests                2.26.0
57. requests-oauthlib       1.3.0
58. rsa                     4.7.2
59. scikit-image            0.17.2
60. scipy                   1.5.4
61. setuptools              58.3.0
62. six                     1.15.0
63. tb-nightly              2.6.0a20210806
64. tensorboard             1.15.0
65. tensorboard-data-server 0.6.1
66. tensorboard-plugin-wit  1.8.0
67. tensorflow              1.15.4
68. tensorflow-estimator    1.15.1
69. tensorflow-gpu          1.15.4
70. termcolor               1.1.0
71. tf-estimator-nightly    2.7.0.dev2021092408
72. tifffile                2020.9.3
73. torch                   1.10.0+cu102
74. torchaudio              0.10.0+cu102
75. torchvision             0.11.1+cu102
76. traitlets               4.3.3
77. typing-extensions       3.7.4.3
78. urllib3                 1.26.7
79. wcwidth                 0.2.5
80. Werkzeug                2.0.2
81. wheel                   0.37.0
82. wrapt                   1.12.1
83. zipp                    3.6.0
```

I tried to install python version 3.7.2, 3.7.9, but running runGan.py 1 gave this error:
```
File "C:\Users\NAME\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\contrib\rnn\ops\gen_gru_ops.py", line 174, in <module>
    _ops.RegisterShape("GRUBlockCell")(None)
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'
```

**Comment by tom-doerr** [comment]
You could try to run it in the docker environment I created: https://github.com/tom-doerr/TecoGAN-Docker

**Comment by Azemar** [comment]
> You could try to run it in the docker environment I created: https://github.com/tom-doerr/TecoGAN-Docker

I somehow could not figure it out with the docker. What versions of components does it use?

**Comment by tom-doerr** [comment]
https://github.com/tom-doerr/TecoGAN-Docker/blob/master/docker/tecogan_gpu
