### ISSUE TITLE
i got AttributeError: module 'tensorflow.python.ops.summary_op_util' has no attribute 'skip_summary'

### ISSUE THREAD

**Issue by skyzombie89** [thunil/TecoGAN#20]
Traceback (most recent call last):
  File "main.py", line 284, in <module>
    Net = TecoGAN( rdata.s_inputs, rdata.s_targets, FLAGS )
  File "/home/ksjin/바탕화면/TecoGAN-master/lib/Teco.py", line 500, in TecoGAN
    gif_sum = [ gif_summary('LR', r_inputs, max_outputs=max_outputs, fps=3),
  File "/home/ksjin/바탕화면/TecoGAN-master/lib/ops.py", line 507, in gif_summary
    if summary_op_util.skip_summary():
AttributeError: module 'tensorflow.python.ops.summary_op_util' has no attribute 'skip_summary'

**how can i fix this error?**

tensorflow = 1.14
python =3.7.3

**Comment by a695649350** [comment]
I have the same error as you have.Besides these,I also have several W0802 like this 

W0802 12:10:39.181865 140561563641664 deprecation_wrapper.py:119] From /home/null/TecoGAN/lib/Teco.py:425: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

**Comment by a695649350** [comment]
I have same problem in ubuntu 18.Then I try debian,it doesnt work as well.

**Comment by yamaton** [comment]
`skip_summary` has moved to `tensorflow.python.distribute.summary_op_util` since v1.14 while other functionalities remain in `tensorflow.python.ops.summary_op_util`. So the fix is not one-liner.
Why don't we stick to 1.13?

**Comment by jcai20** [comment]
I also have this problem. And I just comment these.

**Comment by luyylemon** [comment]
you can try rename like this :
from tensorflow.python.ops import summary_op_util as tpos
from tensorflow.python.distribute import summary_op_util as tpds

**Comment by Vakurin** [comment]
## How to fix it
Open file lib/ops.py

**Add import line**
`from tensorflow.python.distribute.summary_op_util import skip_summary`

and change **line 507** 
`if summary_op_util.skip_summary()` to `if skip_summary()`

**Comment by tom-doerr** [comment]
You could use my docker setup to avoid issues with incompatible tensorflow versions: https://github.com/tom-doerr/TecoGAN
