### ISSUE TITLE
runGan 1 error!

### ISSUE THREAD

**Issue by shuyongzhang** [thunil/TecoGAN#34]
python runGan.py 1
Testing test case 1
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    import tensorflow.contrib.slim as slim
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\__init__.py", line 37, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\__init__.py", line 38, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\__init__.py", line 91, in <module>
    from tensorflow.contrib.rnn.python.ops.lstm_ops import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\python\ops\lstm_ops.py", line 298, in <module>
    @ops.RegisterGradient("BlockLSTM")
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 2489, in __call__
    _gradient_registry.register(f, self._op_type)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\registry.py", line 61, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow_core\\python\\framework\\registry.py:66)"

**Comment by yuqiangabab** [comment]
用ubuntu 用win跑不起来的

**Comment by tom-doerr** [comment]
You could use my TecoGAN docker fork to avoid issues with the setup: https://github.com/tom-doerr/TecoGAN

**Comment by FrankLinxzx** [comment]
> python runGan.py 1
> Testing test case 1
> Traceback (most recent call last):
> File "main.py", line 22, in
> import tensorflow.contrib.slim as slim
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib__init__.py", line 37, in
> from tensorflow.contrib import cudnn_rnn
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn__init__.py", line 38, in
> from tensorflow.contrib.cudnn_rnn.python.layers import *
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers__init__.py", line 23, in
> from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\cudnn_rnn.py", line 20, in
> from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 22, in
> from tensorflow.contrib.rnn.python.ops import lstm_ops
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\rnn__init__.py", line 91, in
> from tensorflow.contrib.rnn.python.ops.lstm_ops import *
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\python\ops\lstm_ops.py", line 298, in
> @ops.RegisterGradient("BlockLSTM")
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 2489, in **call**
> _gradient_registry.register(f, self._op_type)
> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\registry.py", line 61, in register
> (self._name, name, function_name, filename, line_number))
> KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\registry.py:66)"

can run in win10
