### ISSUE TITLE
runGan.py 1 error Google colab (%tensorflow_version 1.x)

### ISSUE THREAD

**Issue by joselcl98** [thunil/TecoGAN#49]
Testing test case 1
WARNING:tensorflow:From main.py:19: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Using TensorFlow backend.
WARNING:tensorflow:From main.py:138: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

input shape: [1, 144, 180, 3]
output shape: [1, 576, 720, 3]
WARNING:tensorflow:From main.py:195: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From main.py:201: The name tf.space_to_depth is deprecated. Please use tf.compat.v1.space_to_depth instead.

WARNING:tensorflow:From main.py:203: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From main.py:206: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From /content/TecoGAN/lib/frvsr.py:22: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

Finish building the network
WARNING:tensorflow:From main.py:221: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From main.py:224: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

WARNING:tensorflow:From main.py:227: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From main.py:228: The name tf.local_variables_initializer is deprecated. Please use tf.compat.v1.local_variables_initializer instead.

WARNING:tensorflow:From main.py:230: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From main.py:239: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Loading weights from ckpt model
Traceback (most recent call last):
  File "main.py", line 245, in <module>
    weight_initiallizer.restore(sess, FLAGS.checkpoint)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/saver.py", line 1280, in restore
    if not checkpoint_management.checkpoint_exists_internal(checkpoint_prefix):
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/training/checkpoint_management.py", line 366, in checkpoint_exists_internal
    if file_io.get_matching_files(pathname):
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/lib/io/file_io.py", line 363, in get_matching_files
    return get_matching_files_v2(filename)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/lib/io/file_io.py", line 384, in get_matching_files_v2
    compat.as_bytes(pattern))
tensorflow.python.framework.errors_impl.NotFoundError: ./model; No such file or directory

**Comment by Balzhunter** [comment]
You need to change the input directory in main.py from LR. And also remember to use more than 6 images. I recently found that is necessary.

**Comment by Balzhunter** [comment]
You need to download the model directory that is in the first command line of runGan.py when you run !python3 runGan.py 0 it will do that. Also check the input directory in runGan.py from LR. And also remember to use more than 6 images. I recently found that is necessary.
