### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by deama** [thunil/TecoGAN#63]
I'm getting this error when I run "python runGan.py 1"

```
Testing test case 1
Traceback (most recent call last):
  File "runGan.py", line 90, in <module>
    mycall(cmd1).communicate()
  File "runGan.py", line 21, in mycall
    return subprocess.Popen(cmd)
  File "C:\Users\deama\Anaconda3\lib\subprocess.py", line 709, in __init_
    restore_signals, start_new_session)
  File "C:\Users\deama\Anaconda3\lib\subprocess.py", line 997, in _execut

    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Anyone know what the issue is?
I'm using anaconda on my windows 8.1.

**Comment by tom-doerr** [comment]
You probably need to run it in a Unix environment such as Linux or WSL for it to work. The reason is that the python code executes some shell commands.

**Comment by deama** [comment]
> You probably need to run it in a Unix environment such as Linux, WSL or the docker environment I provide on my fork: https://github.com/tom-doerr/TecoGAN.
> The reason is that the python code executes some shell commands and I'm not sure if you can get those running in Windows.

Damn, looks like I'll try and make a virtual machine.
I sadly can't get docker to run on my windows 8.1, spent the whole day yesterday trying to get it to run but couldn't.

**Comment by tom-doerr** [comment]
I can't remember what the image sizes were or how much Vram was necessary for inference.
You could open another issue for that, maybe someone else knows.

**Comment by CaryKnoop** [comment]
Tecogan runs fine on Windows 10.

For a 2080Ti the maximum is slightly over SD video size.

**Comment by jolahua** [comment]
> Tecogan runs fine on Windows 10.
> 
> For a 2080Ti the maximum is slightly over SD video size.

Have you achieve use yourself videos to train the model?I need some help~ please!

**Comment by deama** [comment]
I ended up getting it to work fine, but I decided to install ubuntu on an external SATA drive I had.
Sadly the results weren't as good as I thought, it does do some stuff fairly well, but it has to be very low res, it doesn't work well for resolutions above ~360p, below that it's a coin toss, sometimes it works well, other times not so well.
