### ISSUE TITLE
Console spamming when Prepare the Training Data

### ISSUE THREAD

**Issue by IYO1585** [thunil/TecoGAN#66]
I'm getting this error when I run `python3 dataPrepare.py --start_id 2000 --duration 120 --REMOVE --disk_path TrainingDataPath`

```
[Configurations]:
        REMOVE: True
        TEST: False
        duration: 120
        summary_dir: TrainingDataPath\log/
        start_id: 2000
        disk_path: TrainingDataPath
End of configuration
Try loading 308x120.
https://vimeo.com/162166758
[vimeo] 162166758: Downloading webpage
[vimeo] 162166758: Extracting information
[vimeo] 162166758: Downloading JSON metadata
[vimeo] 162166758: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 162166758: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 162166758: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 162166758: Downloading akfire_interconnect_quic MPD information
[vimeo] 162166758: Downloading akfire_interconnect_quic MPD information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 14
[download] Destination: TrainingDataPath\162166758.mp4
[download] 100% of 44.62MiB in 00:10
folder TrainingDataPath\scene_2000/: 120x[1920,1080]//2 at frame 120 of TrainingDataPath\162166758.mp4
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[h264 @ 00000159e1280600] co located POCs unavailable
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[h264 @ 00000159e0f99a80] mmco: unref short failure
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[NULL @ 00000159e0f92960] non-existing PPS 0 referenced
[h264 @ 00000159e1080b20] mmco: unref short failure
...
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\resize.cpp, line 4044
Traceback (most recent call last):
  File "dataPrepare.py", line 145, in <module>
    gen_frames(tar_vid_output, tar_dir, info_dict["width"], info_dict["height"], start_fr, Flags.duration, saveframes)
  File "dataPrepare.py", line 97, in gen_frames
    colFull = video.getImg(cam, i+start)
  File "D:\tool\TecoGAN-master\lib\data\video.py", line 172, in getImg
    icol =  cv.resize(icol, (0,0), fx=0.5, fy=0.5, interpolation=cv.INTER_AREA)
cv2.error: OpenCV(3.4.1) C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize
```

anyone can fix this?
i'm using anaconda on windows 10 x64

**Comment by tom-doerr** [comment]
You could try to run it in docker: https://github.com/tom-doerr/TecoGAN

**Comment by FrankLinxzx** [comment]
> I'm getting this error when I run `python3 dataPrepare.py --start_id 2000 --duration 120 --REMOVE --disk_path TrainingDataPath`
> 
> ```
> [Configurations]:
>         REMOVE: True
>         TEST: False
>         duration: 120
>         summary_dir: TrainingDataPath\log/
>         start_id: 2000
>         disk_path: TrainingDataPath
> End of configuration
> Try loading 308x120.
> https://vimeo.com/162166758
> [vimeo] 162166758: Downloading webpage
> [vimeo] 162166758: Extracting information
> [vimeo] 162166758: Downloading JSON metadata
> [vimeo] 162166758: Downloading JSON metadata
> WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
> [vimeo] 162166758: Downloading akfire_interconnect_quic m3u8 information
> [vimeo] 162166758: Downloading akfire_interconnect_quic m3u8 information
> [vimeo] 162166758: Downloading akfire_interconnect_quic MPD information
> [vimeo] 162166758: Downloading akfire_interconnect_quic MPD information
> [hlsnative] Downloading m3u8 manifest
> [hlsnative] Total fragments: 14
> [download] Destination: TrainingDataPath\162166758.mp4
> [download] 100% of 44.62MiB in 00:10
> folder TrainingDataPath\scene_2000/: 120x[1920,1080]//2 at frame 120 of TrainingDataPath\162166758.mp4
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [h264 @ 00000159e1280600] co located POCs unavailable
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [h264 @ 00000159e0f99a80] mmco: unref short failure
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [NULL @ 00000159e0f92960] non-existing PPS 0 referenced
> [h264 @ 00000159e1080b20] mmco: unref short failure
> (repeat non-exisiting and etc...)
> (and few moments later )
> OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\resize.cpp, line 4044
> Traceback (most recent call last):
>   File "dataPrepare.py", line 145, in <module>
>     gen_frames(tar_vid_output, tar_dir, info_dict["width"], info_dict["height"], start_fr, Flags.duration, saveframes)
>   File "dataPrepare.py", line 97, in gen_frames
>     colFull = video.getImg(cam, i+start)
>   File "D:\tool\TecoGAN-master\lib\data\video.py", line 172, in getImg
>     icol =  cv.resize(icol, (0,0), fx=0.5, fy=0.5, interpolation=cv.INTER_AREA)
> cv2.error: OpenCV(3.4.1) C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize
> ```
> 
> anyone can fix this?
> i'm using anaconda on windows 10 x64

some film are down so cant download
