### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by sephethus** [thunil/TecoGAN#77]
Followed instructions to install from the read me. This is what I get when trying to run the initial tests:

First error I fixed by changing that line to random.set_seed

`python runGan.py 1                                                                                                                                                                           Testing test case 1
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    tf.set_random_seed(1234)
AttributeError: module 'tensorflow' has no attribute 'set_random_seed'`

Next error I'm stuck on:

`python runGan.py 1                                                                                                                                                                            Testing test case 1
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    trt.set_random_seed(1234)
AttributeError: module 'tensorflow.python.compiler.tensorrt.trt_convert' has no attribute 'set_random_seed'`

I've seen one suggestion on the above so far but nothing has worked. I think tensorflow 2 isn't gonna work.

**Comment by tom-doerr** [comment]
Yes, I think you're better off just installing Tensorflow 1.8.
In case you still have issues you could use the docker environment I created: https://github.com/tom-doerr/TecoGAN

**Comment by jveitchmichaelis** [comment]
You need a few specific versions, I managed to get things working with this env:

```
absl-py                0.11.0
astor                  0.8.1
astunparse             1.6.3
cachetools             4.1.1
certifi                2020.6.20
chardet                3.0.4
future                 0.18.2
gast                   0.2.2
google-auth            1.22.1
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.33.1
h5py                   2.10.0
idna                   2.10
importlib-metadata     2.0.0
Keras                  2.3.1
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
Markdown               3.3.3
mkl-fft                1.2.0
mkl-random             1.1.1
mkl-service            2.3.0
numpy                  1.18.5
oauthlib               3.1.0
olefile                0.46
opencv-python-headless 4.4.0.44
opt-einsum             3.3.0
Pillow                 8.0.0
pip                    20.2.4
protobuf               3.13.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
PyYAML                 5.3.1
requests               2.24.0
requests-oauthlib      1.3.0
rsa                    4.6
scipy                  1.5.3
setuptools             50.3.2
six                    1.15.0
tensorboard            1.15.0
tensorboard-plugin-wit 1.7.0
tensorflow             1.15.4
tensorflow-estimator   1.15.1
tensorflow-gpu         1.15.4
termcolor              1.1.0
torch                  1.6.0
torchvision            0.7.0
urllib3                1.25.11
Werkzeug               1.0.1
wheel                  0.35.1
wincertstore           0.2
wrapt                  1.12.1
zipp                   3.4.0
```

Note specific versions of Keras and Tensorflow. This will run the inference test case (1) at least.

I also had to install `opencv-python-headless` manually as it wasn't in the requirements.

**Comment by sephethus** [comment]
This no longer works because I can no longer install these older versions of Tensorflow, TecoGan is broken without fixing this so far as I can tell.

**Comment by tom-doerr** [comment]
@sephethus This is likely because your python version is too new, it should work with Python 3.5.

**Comment by sephethus** [comment]
Is this whole project going to get updated so I don't have to use the docker?

**Comment by tom-doerr** [comment]
I think it's unlikely that it's going to get updated anytime soon.
