### ISSUE TITLE
ImportError: cannot import name 'clock' from 'time' (unknown location)

### ISSUE THREAD

**Issue by Ocean47** [thunil/TecoGAN#92]
I get the below error when trying to run the dataPrepare.py script. Any help would be greatly appreciated? I am not sure if there is a conflict in library versions, or something basic most people have installed in their python libs that I am missing, or what it could be?

I feel like I could bash my head against this for days without a hint as to where I should be looking?

C:\Users\hanso\Documents\GitHub\TecoGAN>python3 dataPrepare.py --help
Traceback (most recent call last):
  File "dataPrepare.py", line 6, in <module>
    from lib.data import video
  File "C:\Users\hanso\Documents\GitHub\TecoGAN\lib\data\video.py", line 41, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)

**Comment by tom-doerr** [comment]
Apparently `clock` got removed from the `time` module in python 3.8. You could try to use python 3.7, importing clock from time works for me in that version. 
In case you still have issues you could have a look at the docker environment I created for the TecoGAN project: https://github.com/tom-doerr/TecoGAN-Docker

**Comment by datatalking** [comment]
@tom-doerr What is did they replace `clock` function within `time` in python 3.8, was it just poof removed or migrated into something else when they deprecated `clock`
